# tmux likes to cycle through appending global paths. so deal with it here
if [[ -z $TMUX ]]; then
  path=(/bin /sbin /usr/bin /usr/sbin /usr/local/bin $HOME/bin ~/f/oetools)
fi

# Set the MANPATH
manpath=($X11HOME/man /usr/man /usr/lang/man /usr/local/man)
export MANPATH

# Path to your oh-my-zsh installation.
#export ZSH=/home/pbauer/.oh-my-zsh
export ZSH=/home/pbauer/c/oh-my-zsh

# Set our default editor
export EDITOR=vim

# Setup history search keybindings
autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

[[ -n "$key[Up]"   ]] && bindkey -- "$key[Up]"   up-line-or-beginning-search
[[ -n "$key[Down]" ]] && bindkey -- "$key[Down]" down-line-or-beginning-search

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="steeef"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="false"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="dd.mm.yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(debian
  git
  command-not-found
  common-aliases
  git
  bundler
  dotenv
  extract
  ssh-agent
  rvm
  systemadmin
  tmux
  zsh-reload
)

#source $ZSH/oh-my-zsh.sh
source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#
alias dns='cd ~/f/puppet-fxcm_dns'
alias gch='cd ~/repos/ && git clone ssh://pbauer@diskstation/volume2/homes/pbauer/repos/home ; cd home'
alias rdp='rdesktop  -u pbauer -d usa.fxcorp.prv -g 1920x1080 -z nyc-it-termsrv.usa.fxcorp.prv'
alias shell='ssh -X nyc1-it-90531.fxcorp'
alias S='sudo'
alias Svi='sudoedit'
alias sa='ssh-add ~/.ssh/id_rsa < /dev/null'
alias t='mkdir -m 0700 -p /tmp/$USER.$$ && cd /tmp/$USER.$$'
alias vpn='sudo openconnect --juniper https://fxgw-new.fxcorporate.com'
#alias vpn='sudo openconnect --juniper https://fxgw-testb.fxcorporate.com'

#TMUX fun
#alias td='tmuxinator detach'
alias tb='tmux new-session -n shell -s shell'
alias tw='tmux new-session -n work -s work'
alias tm='tmux new-session -n mutt -s mutt'
alias tk='tmux kill-server'
alias tab='tmux attach-session -d -t shell'
alias tam='tmux attach-session -d -t mutt'
alias taw='tmux attach-session -d -t work'
alias tmk='tmux kill-session -t'
alias tml='tmux list-session'

#####################
#### custom functions
######################

# randomizes order of stdin or given file
function rand() {
  RANDOM=$RANDOM`date +%s`        # seed
  while IFS= read -r in
  do
    echo ${RANDOM}${RANDOM} "$in"
  done < ${1:-/dev/stdin} | sort | sed -e 's,^[0-9]* ,,'
}


function r() {
#  . ~/.zshenv
  . ~/.zshrc
  fixagent
}

function fixagent() {
  timeout 3s ssh-add -l >/dev/null 2>&1 && return

  for f in $(find /tmp/ssh-* -maxdepth 1 -user $USER -type s -name 'agent*' 2>/dev/null); do
    export SSH_AUTH_SOCK=$f
    timeout 3s ssh-add -l >/dev/null 2>&1 && return
    rm -f $f    # dead
  done

  echo "fixagent: Can't find a forwarded ssh-agent." >&2
  unset SSH_AUTH_SOCK
}
function pingw() {
  local last_state="_"
  local state

  if [[ $# -ne 1 ]]; then
    echo "usage: pingw <host>" >&2
    return 1
  fi

  host=$1
  if ! getent hosts $host >/dev/null 2>&1; then
    echo "pingw: $host: not found" >&2
    return 2
  fi

  while :; do
    if fping -q $host; then
      state="up"
    else
      state="down"
    fi
    if [[ $state != $last_state ]]; then
      echo "$(date) $host $state"
    fi
    last_state=$state
    sleep 1
  done
}

DISABLE_UPDATE_PROMPT="false"
